### ISSUE TITLE
Fix memory leak in the tracking provider

### ISSUE THREAD

**Issue by ldorau** [oneapi-src/unified-memory-framework#122]
Fix memory leak in the tracking provider caused by:
https://github.com/oneapi-src/unified-memory-framework/blob/74fe7d031f490998a8801e91f71f63ff5da00966/src/provider/provider_tracking.c#L56-L66

"_It should not happen_", but it can happen ...

**Comment by igchor** [comment]
Hm, can you add some stacktrace and tell in which tests and in what configuration does this happen? I actually tried to put a breakpoint on line 80 but it wasn't triggered in any tests.

**Comment by ldorau** [comment]
It does not occur on the current main branch. It happens when `arena_extent_dalloc` is implemented - for example in the builds of https://github.com/oneapi-src/unified-memory-framework/pull/141

**Comment by igchor** [comment]
@ldorau is this solved on current main branch?

**Comment by bratpiorka** [comment]
enabling sanitizers done in #179

**Comment by ldorau** [comment]
Issue fixed.
Verified with https://github.com/oneapi-src/unified-memory-framework/pull/158
