### ISSUE TITLE
Not used CMake variable under Windows

### ISSUE THREAD

**Issue by KFilipek** [oneapi-src/unified-memory-framework#123]
During compilation under the CodeQL job, there is a warning related to a not used variable. It should be used in CMake file with Windows.
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_BUILD_TYPE
```

Source:
https://github.com/oneapi-src/unified-memory-framework/actions/runs/7475955267/job/20345254185 (Step: Configure CMake)

EDIT:
https://stackoverflow.com/questions/19024259/how-to-change-the-build-type-to-release-mode-in-cmake

**Comment by PatKamin** [comment]
Note that you can run cmake with the `--no-warn-unused-cli` option to silence this warning. This exact unused variable doesn't change anything in the Windows build, it's just ignored.

**Comment by KFilipek** [comment]
@lukaszstolarczuk It's possibility to use `--parallel`/`-j` in CMake build tool.
https://cmake.org/cmake/help/latest/manual/cmake.1.html#build-a-project

**Comment by lukaszstolarczuk** [comment]
> Note that you can run cmake with the `--no-warn-unused-cli` option to silence this warning. This exact unused variable doesn't change anything in the Windows build, it's just ignored.

I've just seen your comment - I'm not sure if we want to do this in CI. We could ignroe other unused variables, by accident.
