### ISSUE TITLE
[CodeQL] Code scanning cannot determine the alerts

### ISSUE THREAD

**Issue by KFilipek** [oneapi-src/unified-memory-framework#130]
There is a wrong configuration on the CodeQL check, which causes a problem with report generation:
```
Warning: Code scanning cannot determine the alerts introduced by this pull request, because 4 configurations present on refs/heads/main were not found:
Actions workflow (codeql.yml)
❓  .github/workflows/codeql.yml:analyze/nproc:$(nproc)/os:ubuntu-latest
❓  .github/workflows/codeql.yml:analyze/nproc:$(nproc)/os:ubuntu-latest/pool_scalable:ON
❓  .github/workflows/codeql.yml:analyze/nproc:$Env:NUMBER_OF_PROCESSORS/os:windows-latest
❓  .github/workflows/codeql.yml:analyze/nproc:$Env:NUMBER_OF_PROCESSORS/os:windows-latest/pool_scalable:OFF
```

I believe that we should change the configuration to avoid using nproc/env at this level and move it to more deeper in the workflow.

Source:
https://github.com/oneapi-src/unified-memory-framework/pull/115/checks?check_run_id=20353353731

**Comment by KFilipek** [comment]
@lukaszstolarczuk It's possibility to use --parallel/-j in CMake build tool.
https://cmake.org/cmake/help/latest/manual/cmake.1.html#build-a-project

**Comment by lukaszstolarczuk** [comment]
heh, I don't think dropping 'nproc' from matrix will help to solve this issue. I've tested this on my fork and warnings are still present:
https://github.com/lukaszstolarczuk/unified-memory-framework/pull/1/checks?check_run_id=22021021959


Nonetheless,

> @lukaszstolarczuk It's possibility to use --parallel/-j in CMake build tool. https://cmake.org/cmake/help/latest/manual/cmake.1.html#build-a-project

We're using `-j` in CMake build, but actually we didn't use the fact that we can omit `<jobs>`, and it seems it works as expected. Build without value for `-j` is as fast as it was previously. I tested this locally and on my fork:
// https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/8062031346
// https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/8062017094
... to compare - the previous run on "main" (without the change) - there's no significant change in execution time:
// https://github.com/lukaszstolarczuk/unified-memory-framework/actions/runs/8061124797

Soo... I'd merge my PR anyway, but it will not fix this issue:
https://github.com/oneapi-src/unified-memory-framework/pull/265
