### ISSUE TITLE
valgrind shows memory leaks in the jemalloc_pool test when UMF_ENABLE_POOL_TRACKING=ON

### ISSUE THREAD

**Issue by ldorau** [oneapi-src/unified-memory-framework#147]
valgrind shows memory leaks in the `jemalloc_pool` test when `UMF_ENABLE_POOL_TRACKING=ON`

Step to reproduce:
```
[build]$ valgrind --leak-check=full ./test/umf_test-jemalloc_pool
[...]
==18178== LEAK SUMMARY:
==18178==    definitely lost: 10,800 bytes in 675 blocks
==18178==    indirectly lost: 0 bytes in 0 blocks
==18178==      possibly lost: 0 bytes in 0 blocks
==18178==    still reachable: 0 bytes in 0 blocks
==18178==         suppressed: 0 bytes in 0 blocks
==18178==
==18178== For lists of detected and suppressed errors, rerun with: -s
==18178== ERROR SUMMARY: 12 errors from 12 contexts (suppressed: 0 from 0)
```

The leaked resources are tracker's values of the `tracker_value_t` type (16 bytes long) allocated by `arena_extent_alloc() -> umfMemoryTrackerAdd()`  and not freed by `arena_extent_dalloc()/arena_extent_destroy() -> umfMemoryTrackerRemove()`. 

The root cause is that jemalloc does not free (does not call `arena_extent_dalloc()` nor `arena_extent_destroy()`) for larger extents (for example of 2MiB size) that **failed to be split** - **jemalloc leaks them on purpose** assuming that this is only a virtual memory leak, see `extents_abandon_vm()`:
https://github.com/jemalloc/jemalloc/blob/5.2.1/src/extent.c#L631-L632
and
https://github.com/jemalloc/jemalloc/blob/5.2.1/src/extent.c#L642-L643

So we must be aware that all physical memory actually allocated in the `arena_extent_alloc()` hook can be leaked by jemalloc on purpose.

**Comment by igchor** [comment]
@ldorau is this solved on current main branch?

**Comment by ldorau** [comment]
Issue fixed.
Verified with https://github.com/oneapi-src/unified-memory-framework/pull/158
