### ISSUE TITLE
Investigate why number of actions after merging code to main is not constant

### ISSUE THREAD

**Issue by bratpiorka** [oneapi-src/unified-memory-framework#174]
The number of github action run after merging vary from 37 to 41 - we should fix this.

**Comment by bratpiorka** [comment]
JIRA UMFW-236

**Comment by bratpiorka** [comment]
Please look at https://github.com/oneapi-src/unified-memory-framework/commits/main/
I see that the number of passed tests varies from PR to PR. This is probably related to CodeQL, but I have not investigated it.

**Comment by lukaszstolarczuk** [comment]
och, I see. I didn't even know this job count exists 😄 

What I see here is:
- the number of jobs is changing (mostly growing) and that's a good thing - this repo is still under a lot of changes, incl. jobs in CI
- some commits don't run some jobs and that's ok. E.g., we build and deploy pages only for pushes (merges in our case), and they don't run concurrently - if a new merge comes, the prev. one is canceled.
- as I understand some commits can fail (e.g. in this PR: https://github.com/oneapi-src/unified-memory-framework/pull/229/commits) as long as we introduce a fix in the same PR (and that PR is green after all).

Nonetheless, we could leave this issue open (so we keep track of this), but I don't see any major problem for now.

**Comment by bratpiorka** [comment]
fixed by #265
