### ISSUE TITLE
USM support

### ISSUE THREAD

**Issue by igchor** [oneapi-src/unified-memory-framework#225]
UMF should support managing USM (unified shared memory) by:
- exposing memory pools capable of handling memory that might not be accessible on the host:
    - [x] disjoint_pool
    - [x] jemalloc_pool
       - note: there is a known issue with jemalloc: if compiled with default flags it cannot be dlopened (neither can a library that links with jemalloc) which makes it problematic to use in Unified Runtime which manages adapters using dlopen
- exposing memory providers capable of allocating memory on a device:
   - [x] L0 provider (currently implemented in Unified Runtime)
   - [ ] CUDA provider (currently implemented in Unified Runtime)
   - [ ] Unified Runtime (?)

It should be possible to build L0 and CUDA providers as static libraries so that they can be used by Unified Runtime.

We should also consider:
- adding memory copy / memset operations for providers (to implement calloc/realloc on device-only memory)
- async memory management (transfers and/or allocation)

**Comment by vinser52** [comment]
Another requirement from MPI/oneCCL. They do not have hard dependency to L0 today the same MPI/oneCCL binaries should work on the system without L0. They resolve dependency to L0 at runtime using dlopen/dlsym to look for `libze_loader.so`.
We should consider this case when developing L0 memory provider.
