### ISSUE TITLE
Add logging mechanism

### ISSUE THREAD

**Issue by bratpiorka** [oneapi-src/unified-memory-framework#247]
The logging mechanism should:
- [ ] have C-style interface (with %s etc)
- [ ] support different levels of message importance that should match UR (debug, info, warn, err)
- [ ] should be configurable through env var (TODO: see UR), there is no need to allow enabling it by API
- [ ] support for different output (file, stderr, stdout)
- [ ] prefix should contain process / thread ID
- [ ] should not use malloc

The logging mechanism will be used in whitebox tests to validate UMF, by developers for debugging purposes and by the user to report errors etc.

**Comment by bratpiorka** [comment]
@lplewa

**Comment by lplewa** [comment]
Qpen 1. Name of environment variable, and its possible values. Similar to UR: i.e. UMF_LOG=""level:debug;flush:debug;output:stderr". Something different but simpler? 

Open 2. Do UR logging will also enable UMF logging - IMHO no - but if you have a different opinion please share how do you see this implemented on UR side(setenv()???).

**Comment by pbalcer** [comment]
> Qpen 1. Name of environment variable, and its possible values. Similar to UR: i.e. UMF_LOG=""level:debug;flush:debug;output:stderr". Something different but simpler?

I like UMF_LOG. We should use the same syntax as UR for consistency. If we think it's too complicated, we should change it in both places.

> 
> Open 2. Do UR logging will also enable UMF logging - IMHO no - but if you have a different opinion please share how do you see this implemented on UR side(setenv()???).

That would be very strange. We could point to UMF documentation in UR so that users are aware that the allocator-related logs need to be configured separately.
Alternatively, if there are messages we think must reach the user, there should be a programmatic API to pass those messages from UMF to UR, so that UR can log it using its own mechanism.

**Comment by bratpiorka** [comment]
UMF_LOG is ok for me. I think at least the first step would be without the "flush" parameter. UR can leverage umf*GetLastAllocationError to log any errors - would this be enough?

**Comment by vinser52** [comment]
> Qpen 1. Name of environment variable, and its possible values. Similar to UR: i.e. UMF_LOG=""level:debug;flush:debug;output:stderr". Something different but simpler?

I like to be aligned with UR
 
> Open 2. Do UR logging will also enable UMF logging - IMHO no - but if you have a different opinion please share how do you see this implemented on UR side(setenv()???).

I think UMF logging should be enabled explicitly and should not depend on UR.

**Comment by lplewa** [comment]
Any through about log format? I created them similar to UR - but i have no idea how nicely add PID and TID to message(UR do not include this info), so I'm open for ideas/comments.

Currently i have:
```<UMF>(72361|72361)[ERROR]: example log from main
<UMF>(72361|72362)[ERROR]: example log from a thread```

**Comment by igchor** [comment]
> Any through about log format? I created them similar to UR - but i have no idea how nicely add PID and TID to message(UR do not include this info), so I'm open for ideas/comments.
> 
> Currently i have:
> 
> ```
> <UMF>(72361|72361)[ERROR]: example log from main
> <UMF>(72361|72362)[ERROR]: example log from a thread
> ```

Perhaps it would be better to have just a single delimiter (space?) instead of `|`, `()` and `[]`  - easier to parse it that way. But I don't have a strong opinion on that.

Also, perhaps we could also consider printing a timestamp in the log - what do you think?

**Comment by lplewa** [comment]
> > Any through about log format? I created them similar to UR - but i have no idea how nicely add PID and TID to message(UR do not include this info), so I'm open for ideas/comments.
> > Currently i have:
> > ```
> > <UMF>(72361|72361)[ERROR]: example log from main
> > <UMF>(72361|72362)[ERROR]: example log from a thread
> > ```
> 
> Perhaps it would be better to have just a single delimiter (space?) instead of `|`, `()` and `[]` - easier to parse it that way. But I don't have a strong opinion on that.
> 
> Also, perhaps we could consider printing a timestamp in the log - what do you think?

We can do anything - but currently UR has following format and we probably should be consistent. 
```<Module>[Error level] message ```

**Comment by lplewa** [comment]
@pbalcer @bratpiorka @igchor i concatenated your input - are you OK with this format?

```export UMF_LOG=level:debug;output:stdrer
[DEBUG UMF] example log from main
[INFO  UMF] example log from a thread
export UMF_LOG=level:debug;output:stdrer;PID:true
[PID:19919  TID:19919  DEBUG UMF] example log from main
[PID:19919  TID:19921  INFO  UMF] example log from a thread
export UMF_LOG=level:debug;output:stdrer;timestamp:true
[2024-03-04T16:47:06 DEBUG UMF] example log from main
[2024-03-04T16:47:06 INFO  UMF] example log from a thread
export UMF_LOG=level:debug;output:stdrer;timestamp:true;pid:true
[2024-03-04T16:47:06 PID:19919  TID:19919  DEBUG UMF] example log from main
[2024-03-04T16:47:06 PID:19919  TID:19923  INFO  UMF] example log from a thread```

**Comment by igchor** [comment]
> @pbalcer @bratpiorka @igchor i concatenated your input - are you OK with this format?
> 
> ```
> [DEBUG UMF] example log from main
> [INFO  UMF] example log from a thread
> export UMF_LOG="level:debug;output:stderr;pid:true"
> [PID:19919  TID:19919  DEBUG UMF] example log from main
> [PID:19919  TID:19921  INFO  UMF] example log from a thread
> export UMF_LOG=level:debug;output:stderr;timestamp:true
> [2024-03-04T16:47:06 DEBUG UMF] example log from main
> [2024-03-04T16:47:06 INFO  UMF] example log from a thread
> export UMF_LOG="level:debug;output:stderr;timestamp:true;pid:true"
> [2024-03-04T16:47:06 PID:19919  TID:19919  DEBUG UMF] example log from main
> [2024-03-04T16:47:06 PID:19919  TID:19923  INFO  UMF] example log from a thread```
> ```

Looks good. I think it might be useful to have more precise timestamps (with seconds/miliseconds) but I guess this could be an option in env var.
