### ISSUE TITLE
Proxy pool does not work under gdb

### ISSUE THREAD

**Issue by igchor** [oneapi-src/unified-memory-framework#269]
## Environment Information

- UMF version (hash commit or a tag):                      https://github.com/oneapi-src/unified-memory-framework/commit/36261a2d03837031ae05b1638cd5f9851a1ca81a
- OS(es) version(s):                                          fedora-39
- kernel version(s):                                          
- compiler, libraries, and other related tools version(s):    

## Please provide a reproduction of the bug:

 LD_PRELOAD=./lib/libumf_proxy.so gdb --args ls

## How often bug is revealed:

always

## Actual behavior:

```
Fatal signal: Segmentation fault
----- Backtrace -----
0x558bb74ac160 ???
0x558bb75e92b2 ???
0x558bb75e9489 ???
0x7f2f53e5c99f ???
0x7f2f507247b2 ???
0x7f2f50726067 ???
0x7f2f54e772b9 tbb_free
        /root/unified-memory-framework/src/pool/pool_scalable.c:247
0x7f2f54c56f7d umfPoolFree
        /root/unified-memory-framework/src/memory_pool.c:63
0x7f2f54e76954 free
        /root/unified-memory-framework/src/proxy_lib/proxy_lib.c:236
0x7f2f04643749 ???
0x7f2f0466dbd8 ???
0x7f2f502ecf38 ???
0x7f2f5066ea44 ???
0x7f2f5066e537 ???
0x558bb74b1d09 ???
0x558bb74b3210 ???
0x558bb75e0c97 ???
0x558bb78a5579 ???
0x558bb78a4c99 ???
0x558bb78a6655 ???
0x558bb78a66d2 ???
0x558bb76d6969 ???
0x558bb76d94f3 ???
0x558bb76d98cf ???
0x558bb73a9bcf ???
0x7f2f53e46149 ???
0x7f2f53e4620a ???
0x558bb73b99a4 ???
0xffffffffffffffff ???
---------------------
A fatal error internal to GDB has been detected, further
debugging is not possible.  GDB will now terminate.

This is a bug, please report it.  For instructions, see:
<https://www.gnu.org/software/gdb/bugs/>
```

## Expected behavior:

command works properly

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  

Requested priority: (Showstopper, High, Medium, Low)

**Comment by ldorau** [comment]
@igchor It should be run in another way:

Add:
```
set environment LD_PRELOAD=./lib/libumf_proxy.so
```
line to the `~/.gdbinit` file and run:
```sh
$ gdb --args <any-command-with-arguments>
```

**Comment by ldorau** [comment]
@igchor Can we close the issue?

**Comment by igchor** [comment]
> set environment LD_PRELOAD=./lib/libumf_proxy.so

This works, thanks.
