### ISSUE TITLE
The umf-memspace_host_all test very often fails on Qemu

### ISSUE THREAD

**Issue by ldorau** [oneapi-src/unified-memory-framework#307]
The umf-memspace_host_all test **VERY OFTEN** fails on Qemu:
https://github.com/oneapi-src/unified-memory-framework/actions/runs/8194430277/attempts/1
https://github.com/oneapi-src/unified-memory-framework/actions/runs/8194430277/attempts/2

**Comment by ldorau** [comment]
@igchor

**Comment by igchor** [comment]
@kswiecicki could you take a look? looks like it might be connected to that OOM test
