### ISSUE TITLE
Disable warnings for CRT Functions and drop <*_s> Functions

### ISSUE THREAD

**Issue by lplewa** [oneapi-src/unified-memory-framework#317]
Disable warnings for CRT Functions and drop <*_s> Functions

Windows generates warnings for the use of certain CRT functions (e.g., fopen, strncpy) deemed unsafe, recommending "safe" alternatives (fopen_s, strncpy_s, etc.). This approach works in case of Windows-only software, but in case of multi platform one, it's add extra burden. 

## Rationale

- Cross-Platform Development: Our aim is to develop software that is secure and compatible across all platforms. Relying on functions that are only considered safe on Windows introduces unnecessary complexity and risk when porting to or supporting other operating systems.

- Safety Through Portability: The essence of these safe functions is to prevent common errors. However, in a cross-platform context, we're compelled to use the universal, so-called unsafe versions responsibly, thereby mitigating potential security vulnerabilities without platform-specific functions.

- Increased Error Potential: The policy inadvertently promotes the use of workarounds (e.g., preferring memcpy over strncpy), potentially increasing the likelihood of mistakes due to the less protective nature of the alternatives.

- Consistency and Risk Management: A trend has been observed where developers avoid strncpy for memcpy, which is not inherently safer and could lead to errors.

**Comment by bratpiorka** [comment]
thank you @lplewa, I agree with these arguments
