### ISSUE TITLE
Two disjointPool tests fail under memcheck and helgrind

### ISSUE THREAD

**Issue by igchor** [oneapi-src/unified-memory-framework#338]
**The current status:** (see below the original issue)

The following two disjointPool tests fail under memcheck and helgrind:
1) disjointPoolTests/umfPoolTest.pow2AlignedAlloc/0
2) disjointPoolTests/umfPoolTest.multiThreadedpow2AlignedAlloc/0

They are temporarily disabled by the 2648539890172e26648d573d615acc7d800741f6 commit.

-------------------------------------------------

**The original issue:**
```
./umf_test-disjointPool - FAILED!
ERROR SUMMARY: 1076 errors from 106 contexts (suppressed: 0 from 0)

/home/runner/work/unified-memory-framework/unified-memory-framework/test/test_valgrind.sh: line 74:  4[27](https://github.com/igchor/unified-memory-framework/actions/runs/8269325299/job/22624345633#step:6:28)1 Aborted                 (core dumped) HWLOC_CPUID_PATH=./cpuid valgrind $OPTION $OPT_SUP --gen-suppressions=all $test > $LOG 2>&1
./umf_test-memspace_host_all (valgrind failed) - FAILED!
ERROR SUMMARY: 7 errors from 7 contexts (suppressed: 1 from 1)

./umf_test-provider_os_memory_config (valgrind failed) - FAILED!
ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 3 from 3)
ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 2 from 2)
ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 1 from 1)
```

The disjointPool test failure seems to be related to newly added valgrind/asan annotations. The remaining tests seem to be incompatible with valgrind (mbind does not work under valgrind in provider_os_memory_config and memspace_host_all tests OOM which does not work with valgrind well as well)  - we should consider disabling them under memcheck.

**Comment by ldorau** [comment]
The current status:

The following two disjointPool tests fail under memcheck and helgrind:
1) disjointPoolTests/umfPoolTest.pow2AlignedAlloc/0
2) disjointPoolTests/umfPoolTest.multiThreadedpow2AlignedAlloc/0

They are temporarily disabled by the 2648539890172e26648d573d615acc7d800741f6 commit.
Fix those failures and revert this commit.

**Comment by ldorau** [comment]
The current repro:
https://github.com/ldorau/unified-memory-framework/actions/runs/8523982209/job/23347525744

**Comment by igchor** [comment]
The helgrind test should be fixed by this suppress: https://github.com/oneapi-src/unified-memory-framework/pull/405

As for memcheck, I suspect this is also a false-positive (incompatibility with std lib) but I'm not 100% sure. I would suggest resisting this after we port disjoint_pool to base_alloc. This could fix the issue or at least make it easier to debug.
