### ISSUE TITLE
Build all libs as shared object when libumf is built that way

### ISSUE THREAD

**Issue by bratpiorka** [oneapi-src/unified-memory-framework#387]
Build all libraries as shared objects when libumf is built this way.
It makes no sense to dynamically link only part of the libraries.

**Comment by igchor** [comment]
I'm not so sure if this is the best approach. For example, I think we prefer to keep using disjoint_pool as a static library in UR - at least for now.

Eventually, I think we should make disjoint_pool a part of libumf itself (it would require rewriting it in C), tbbmalloc could be a part of libumf as well. I'm still not sure what we should do with jemalloc though since there are known problems with dlopen.

**Comment by bratpiorka** [comment]
But why do we want to link disjoint pool as static and umf as shared object?

**Comment by bratpiorka** [comment]
hm, but from a user's perspective (say - me), when I decide to use dynamic libraries, the reason is e.g. to use the latest libraries installed on the system. So if I use the latest libumf, I am also interested in using the latest libdisjoint_pool.

@vinser52 @pbalcer what do you think?

**Comment by ldorau** [comment]
@bratpiorka Is it really a bug?

**Comment by ldorau** [comment]
> hm, but from a user's perspective (say - me), when I decide to use dynamic libraries, the reason is e.g. to use the latest libraries installed on the system. So if I use the latest libumf, I am also interested in using the latest libdisjoint_pool.
> 

@vinser52 @pbalcer what do you think?

**Comment by bratpiorka** [comment]
> @bratpiorka Is it really a bug?

this is inconsistency

**Comment by ldorau** [comment]
> > @bratpiorka Is it really a bug?
> 
> this is inconsistency

Yes, I agree.
Frankly I do not understand it either.

**Comment by igchor** [comment]
> What about scalable pool implementation? As I remember in the past we agreed that we do not need to introduce separate library for a scalable pool. libumf at runtime will try to dlopen tbbmalloc library and if it is found than scalable pool is available.

Yes, and I belive there's nothing stopping us from doing it right now. I wanted to create a PR with this change but I didn't have time yet.
