### ISSUE TITLE
Create documentation for IPC functionality

### ISSUE THREAD

**Issue by vinser52** [oneapi-src/unified-memory-framework#404]
## Description

PR #88 introduces initial support for IPC functionality. It allows the creation of an IPC handle for the memory buffer (allocated via UMF) on the producer side and opening (mapping to the address space) this handle on the consumer side (in the same or another process).

IPC handles functionality is memory provider-specific. This API is optional.

## API Changes

UMF IPC API resides in the `<umf/ipc.h>` header file.

Memory provider-specific API was extended with `umf_memory_provider_ipc_ops_t` structure.

**Comment by bratpiorka** [comment]
@vinser52 could we close this issue?
