### ISSUE TITLE
Add CMake for examples

### ISSUE THREAD

**Issue by lukaszstolarczuk** [oneapi-src/unified-memory-framework#427]
Add CMake files for each example, as this should be a part of the documentation. The user would know how to build a specific example. We could later on test these examples as standalone binaries, using installed version of UMF.

These CMake files should be installed along with source files, of course.

Each example should have a separate directory - it should be updated in the installation process as well.

**Comment by bratpiorka** [comment]
@lukaszstolarczuk please add to this description that each example should be put to separate directory + we could consider cleaning up cmake flags

**Comment by lukaszstolarczuk** [comment]
@bratpiorka, not sure if cleaning up CMake flags is part of this issue... unless you mean only to clean up flags related to examples.

**Comment by lukaszstolarczuk** [comment]
> @lukaszstolarczuk please verify if #589 fixes this issue

Pls see my issue on the PR review.
