### ISSUE TITLE
Fix logging documentation

### ISSUE THREAD

**Issue by bratpiorka** [oneapi-src/unified-memory-framework#431]
Currently, the logging documentation is added here: https://oneapi-src.github.io/unified-memory-framework/introduction.html#logging.

It shouldn't be a part of "Memory Pools" section - I think we could put it in the new "Fundamentals" section similar to how it is done in UR https://oneapi-src.github.io/unified-memory-framework/introduction.html#logging

Also, we should add some documentation to the README

**Comment by lukaszstolarczuk** [comment]
> Also, we should add some documentation to the README

Perhaps not to README, but to CONTRIBUTING.
