### ISSUE TITLE
CMake config file contains only 'major.minor.patch' version

### ISSUE THREAD

**Issue by lukaszstolarczuk** [oneapi-src/unified-memory-framework#466]
When executing `make install` we prepare (and install) a special config file, to be used via CMake's `find_package` in other projects. It currently uses a CMake's helper function: `write_basic_package_version_file` <[docs](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#generating-a-package-version-file)>. This helper function uses a template, which uses VERSION in format `<major.minor.patch>` - it does not use any tweak or pre-release version part. So it's always uses the same version, even though we e.g. moved on from "0.1.0" version by many commits on the main branch.

That said - it seems it will be a little difficult to find out the real version of e.g. a customer's version installed in the system.

Perhaps, one solution would be to write our own config version script...?

FYI, the config file mentioned above is currently installed like here: `install-dir/lib/cmake/umf/umf-config-version.cmake`, and starts like this:
```
set(PACKAGE_VERSION "0.1.0")

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
...
```

Along with that, we should probably add info in README file, how to integrate our project via CMake (or propose other integration ways).

This issue is slightly related to https://github.com/oneapi-src/unified-memory-framework/pull/453.

**Comment by lukaszstolarczuk** [comment]
I think after changes in #616 we can say this issue will be outdated. We no longer use CMake as a main source of our version. If anyone uses our lib, we print the proper (complete, semver aligned version) in `CMake configure` step and in our logger. So it should be fairly ease to establish the proper version installed in the system.

**Comment by bratpiorka** [comment]
closing - with logging enabled we could get all info needed
