### ISSUE TITLE
Add option to link statically with hwloc (on windows)

### ISSUE THREAD

**Issue by igchor** [oneapi-src/unified-memory-framework#513]
## Rationale

UMF is currently being used by UR and Intel/llvm. Those projects use the `/DEPENDENTLOADFLAG:0x800` linker flag on Windows when building .dlls, which results in the loader only looking for .dll dependencies in System32. Since we currently do not have an installer for UMF, we cannot make UR depend on umf.dll or libwloc.dll. Instead, we need to link with UMF and hwloc statically.

## Description

Add CMake option to link with hwloc statically. This may be supported only on Windows.

## API Changes

None.

## Implementation details

I'm not exactly sure how static linking works on windows, we might need to do something like this: https://stackoverflow.com/questions/2157629/linking-static-libraries-to-other-static-libraries or in addition to changes in UMF, also link to hwloc when building the application (UR adapter / llvm plugin).

## Meta

Related PRs:
- https://github.com/oneapi-src/unified-runtime/pull/1430
- https://github.com/intel/llvm/pull/13343

**Comment by igchor** [comment]
Once this is implemented and a new flag for static linking is added, we will need to:
- update https://github.com/intel/llvm/pull/13343 and set this newly added flag on windows
- (optional) update https://github.com/oneapi-src/unified-runtime/pull/1430 and add a CI job for windows to test the static linking

**Comment by lukaszstolarczuk** [comment]
@igchor, does https://github.com/oneapi-src/unified-memory-framework/pull/534 fix this issue?

**Comment by igchor** [comment]
> @igchor, does #534 fix this issue?

Yes, the build on https://github.com/intel/llvm/pull/13343 passes with this change

**Comment by KFilipek** [comment]
> > @igchor, does #534 fix this issue?
> 
> Yes, the build on [intel/llvm#13343](https://github.com/intel/llvm/pull/13343) passes with this change

PR #534 was merged so you can rebase your changes.

**Comment by lukaszstolarczuk** [comment]
closing then, thx!
