### ISSUE TITLE
Introduce init/teardown functions instead of relying on library ctor/dtor

### ISSUE THREAD

**Issue by igchor** [oneapi-src/unified-memory-framework#514]
## Rationale

UMF creates and destroys global state on linux using `__attribute__((constructor))` and  `__attribute__((destructor))` respectively. This is problematic for libraries that do cleanup in it's own library destructor. For example, llvm, might in some cases, try to free memory to UMF in it's destructor after UMF has already been destroyed. 

Because llvm uses dlopen to (indirectly) load UMF, setting constructor/destructor priority is not enough to guarantee proper ordering.

## Description

UMF should expose explicit init/teardownAPI, similarly to UR.

The UMF API should implement ref counting, similarly, to: https://oneapi-src.github.io/unified-runtime/core/api.html?highlight=teardown#uradapterrelease as there might be multiple users (adapters) initializing and deinitializing UMF - the resources should only be released once the last user is gone.

## API Changes

umf_result_t umfInit(/* TBD */);
umf_result_t umfTeardown(void);

## Implementation details

Move all global state initialization and destruction to the new functions. For proxy_library we can still have library ctor and dtor that would just call init/teardown function. Since those function would implement refcounting it should be safe to use proxy_lib with applications that use UMF directly.

**Comment by ldorau** [comment]
Implementation is ready: #530 - @igchor please review.

**Comment by bratpiorka** [comment]
@igchor in #530 Łukasz added required functions, but they work slightly differently from urLoaderInit/Teardown - in UMF user must call these functions only when UMF is loaded using dlopen(). In the scenario where UMF is linked dynamically in CMake they are not needed.

**Comment by pbalcer** [comment]
> Łukasz added required functions, but they work slightly differently from urLoaderInit/Teardown - in UMF user must call these functions only when UMF is loaded using dlopen(). In the scenario where UMF is linked dynamically in CMake they are not needed.

They might be needed though, in UR. Where UMF itself is *not* dlopen'ed, but UR is. Anyway, I agree the library should work without these calls, but calling them, no matter how umf is linked, should not break things and cause the state destruction happen in the umfTeardown.
