### ISSUE TITLE
UMF log file is overwritten in case of multiprocessing

### ISSUE THREAD

**Issue by vinser52** [oneapi-src/unified-memory-framework#523]
oneCCL and MPI applications can create multiple processes (ranks) per node. In that case we are not able to capture UMF logs to the output file from multiple processes.

## Please provide a reproduction of the bug:

Set `UMF_LOG="level:debug;flush:warning;output:file,umf.log;pid:yes"` environment and run several processes that uses UMF.

## How often bug is revealed:

always

## Actual behavior:

Only logs from a single process (that opened the log file last) appear in the specified output file.

## Expected behavior:

Logs from multiple processes are captured. We can create multiple files with PID in the name or write to a single file from multiple processes.

## Additional information about Priority and Help Requested:

Requested priority: Medium

**Comment by vinser52** [comment]
> @vinser52 please check #527 - it should fix this problem.

Yeah, it looks like it should.

**Comment by bratpiorka** [comment]
fixed by https://github.com/oneapi-src/unified-memory-framework/pull/527
