### ISSUE TITLE
UMF versioning is doubled (and not compatibile with semver.)

### ISSUE THREAD

**Issue by lplewa** [oneapi-src/unified-memory-framework#565]
**Current State:**

We are currently using two different versioning schemes in our project:
- Main Version: This version is hardcoded in the CMake project command.
- Git Version (called "source version"): This version, compliant with Semantic Versioning (SemVer), is generated separately based on git-describe.

**Expected state:**

We should have a single versioning scheme, based on Git version which is compliant with SemVer

ref: https://semver.org/

**Comment by lukaszstolarczuk** [comment]
When fixing this issue we should also take into considereration this issue: https://github.com/oneapi-src/unified-memory-framework/issues/466

**Comment by lukaszstolarczuk** [comment]
Proposed solution to this problem is in: https://github.com/oneapi-src/unified-memory-framework/pull/616

We set CMake version just to use it for SOVERSION and to generate CMake FindUMF.cmake/config file.
`UMF_VERSION` after the change will be aligned to semver and used solely in the project.
