### ISSUE TITLE
Inconsistency in Usage of Assertion Methods in Tests

### ISSUE THREAD

**Issue by lplewa** [oneapi-src/unified-memory-framework#569]
### Current Situation
Our test suite currently uses two different assertion frameworks:
1. **Google Test (GTEST) Assertions**: These assertions use `ASSERT` and `EXPECT` macros.
2. **UT_ASSERTs**: These assertions call `abort()` on failure, which undesirably terminates the execution of any subsequent tests within the same file.
3. Some test constructors utilize only EXPECT macro, and after initialization fails, it continue test execution, causing it fail in different place. 

### Problems Identified
- **Test Execution Interruption**: The use of `UT_ASSERT` can prematurely end test execution upon failure, preventing full test suite runs.
- **Incompatibility in Test Initialization**: Google Test's `ASSERT` macros are not suitable for use in initialization routines (like in helper functions or within test class constructors) because they employ `return` statements that is supposed to exit test "main function"

### Proposed Solution
1. **Standardize on GTEST Assertions**: Transition all assertions to GTest.

**Comment by lplewa** [comment]
Idea with a base class might be not the best approach - i noticed it might not be needed. It is to be considered during refactoring

**Comment by bratpiorka** [comment]
closing as we merged the last part of fixes
