### ISSUE TITLE
Fix Branch-Protection code scanning alert

### ISSUE THREAD

**Issue by bratpiorka** [oneapi-src/unified-memory-framework#580]
## Details

https://github.com/oneapi-src/unified-memory-framework/security/code-scanning/1

## Additional information about Priority and Help Requested:

Requested priority: Low

**Comment by lukaszstolarczuk** [comment]
I think we're good now. I enabled required reviews from codeowners and set a basic (Fast build) check as required.

![image](https://github.com/oneapi-src/unified-memory-framework/assets/29728779/cceac43c-9e5b-4d71-84dc-e1cc3fecab29)

I only hope it's going to be smart if we e.g. change the name of this job, or change params, or something...
