### ISSUE TITLE
[CI] Step description hides behavior

### ISSUE THREAD

**Issue by KFilipek** [oneapi-src/unified-memory-framework#629]
## Description
The following step hides the installation of hwloc from sources.
It should be a separate step and change into the form `apt update && apt install -y [...]` to get clear information on what is performed at this step.

![image](https://github.com/user-attachments/assets/eb248a81-a8c4-42ec-b091-dbbcd6ac4a78)

## Environment Information

- UMF version (hash commit or a tag): main
- OS(es) version(s): N/A
- kernel version(s): N/A
- compiler, libraries, and other related tools version(s): N/A

## Please provide a reproduction of the bug:

[Fast builds / Fast builds (ubuntu-20.04, OFF, ON, -DCMAKE_BUILD_TYPE=Release, ON)]
(https://github.com/KFilipek/unified-memory-framework/actions/runs/10056349281/job/27794983520#logs)

## How often bug is revealed:

always

## Actual behavior:

N/A

## Expected behavior:

N/A

## Details

N/A

**Comment by lukaszstolarczuk** [comment]
Would it be suficient, in your opinion, to just change the name of the step to "install dependencies"? Does it matter to us how hwloc was installed?
