### ISSUE TITLE
Disjoint pool with OS memory provider floods screen with error messages

### ISSUE THREAD

**Issue by ldorau** [oneapi-src/unified-memory-framework#63]
Disjoint pool with OS memory provider floods screen with huge amount of the following error messages:
```
DisjointPool: error from memory provider: 2
Native error msg: memory deallocation failed: Invalid argument, native error code: 1005
```
because each `memoryProviderFree()` calls `umfMemoryProviderFree(os_memory_provider, ptr, 0);`  that calls `munmap(ptr, 0);` and generates such error, because `size` equals `0`.

Steps to reproduce - just run benchmark:
```
[build]$ ./benchmark/ubench
```

**Comment by ldorau** [comment]
@bratpiorka

**Comment by bratpiorka** [comment]
@ldorau could you add instructions on how to reproduce this problem?

**Comment by bratpiorka** [comment]
@ldorau could you add instructions on how to reproduce this problem?

**Comment by ldorau** [comment]
> @ldorau could you add instructions on how to reproduce this problem?

Just run:
```
[build]$ ./benchmark/ubench
```
