### ISSUE TITLE
Add implementation for all exported functions on all OSes

### ISSUE THREAD

**Issue by bratpiorka** [oneapi-src/unified-memory-framework#649]
Add implementation for all exported functions on all operating systems,
For functions that are not yet ready, we should report NOT_SUPPORTED error instead of using OPTIONAL_SYMBOLS in def/map files.

related to #646

**Comment by lplewa** [comment]
ref #568

**Comment by bratpiorka** [comment]
fixed by https://github.com/oneapi-src/unified-memory-framework/pull/787
