### ISSUE TITLE
Examples to use both FSDAX permanent memory and normal DRAM

### ISSUE THREAD

**Issue by jesHrz** [oneapi-src/unified-memory-framework#742]
## Details
I'd like to use a hybrid memory pool simultaneously, where I allocate memory either from permanent memory from the FSDAX device or the normal DRAM from anonymous mapping.

I found that libmemkind meets my requirement because I can specify the different allocator via `struct memkind` in `memkind_malloc`.
Unfortunately, libmemkind is deprecated now...

I am wondering if I could find the same usage example from UMF as libmemkind does?

**Comment by ldorau** [comment]
Hi @jesHrz, I have just added to UMF the support for FSDAX (https://github.com/oneapi-src/unified-memory-framework/pull/746). In order to handle FSDAX, the file memory provider with the memory `visibility` mode parameter set to `UMF_MEM_MAP_SYNC` must be used. I am currently working on the example using both FSDAX permanent memory and normal DRAM, as you need. I will keep you updated. Please stay tuned.

**Comment by ldorau** [comment]
I have submitted the PR https://github.com/oneapi-src/unified-memory-framework/pull/750 with this example.

**Comment by jesHrz** [comment]
Hi @ldorau , much thanks for your effort! 

BTW, I also want to know if UMF can automatically detect which pool a pointer is allocated from. since memkind can free a pointer with an unknown kind (`memkind_free(NULL, ptr)`).

**Comment by ldorau** [comment]
> Hi @ldorau , much thanks for your effort!
> 
> BTW, I also want to know if UMF can automatically detect which pool a pointer is allocated from. since memkind can free a pointer with an unknown kind (`memkind_free(NULL, ptr)`).

Yes, there is the function:
```c
///
/// @brief Retrieve memory pool associated with a given ptr. Only memory allocated
///        with the usage of a memory provider is being tracked.
/// @param ptr pointer to memory belonging to a memory pool
/// @return Handle to a memory pool that contains ptr or NULL if pointer does not belong to any UMF pool.
///
umf_memory_pool_handle_t umfPoolByPtr(const void *ptr);
```

**Comment by ldorau** [comment]
Hi @jesHrz, the "_Add dram_and_fsdax example_" #750 has already been merged upstream.
