### ISSUE TITLE
Fix alignment in malloc_compliance test on Windows

### ISSUE THREAD

**Issue by bratpiorka** [oneapi-src/unified-memory-framework#79]
Fix alignment in malloc_compliance test on Windows. Currently this check is disabled - see https://github.com/oneapi-src/unified-memory-framework/pull/64/files#diff-93868d1108b1c4d87fb0517df2f854c41ae21d60ae3924d0ac9b3424e483e819R60

**Comment by ldorau** [comment]
This check does not pass only in the **Release** build on Windows. It seems that there can be a **different byte alignment in the Release build than in the Debug build on Windows**, see for example:
https://www.codeproject.com/Questions/624032/VS-2012-byte-alignment-Release-vs-Debug
and
https://stackoverflow.com/questions/5234121/data-not-aligned-correctly-in-visual-studio-if-run-in-debugger

**Comment by ldorau** [comment]
In **GNU systems**:
"_The address of a block returned by malloc or realloc in **GNU systems** is always a multiple of eight (or sixteen on 64-bit systems)._" (see: https://www.gnu.org/software/libc/manual/html_node/Aligned-Memory-Blocks.html)

**Comment by bratpiorka** [comment]
Let's check for the 8-byte alignment, as this is the strongest requirement that should be met by all allocators in all operating systems/configurations.

**Comment by ldorau** [comment]
> Let's check for the 8-byte alignment, as this is the strongest requirement that should be met by all allocators in all operating systems/configurations.

Done by https://github.com/oneapi-src/unified-memory-framework/pull/100
