### ISSUE TITLE
libumf.so and libumf.so.0 are not symlinks in UMF from oneAPI 2025.0 package

### ISSUE THREAD

**Issue by irozanova** [oneapi-src/unified-memory-framework#956]
libumf.so and libumf.so.0 files are not symlinks in UMF from oneAPI 2025.0 package

## Environment Information

- UMF version (hash commit or a tag): oneAPI 2025.0                         
- OS(es) version(s): Linux                                         

## Please provide a reproduction of the bug:

ls -al  /install/software/oneAPI/2025.0/umf/0.9/lib/
total 336
drwxr-xr-x 2 root root     65 Oct 30 06:24 .
drwxr-xr-x 8 root root     96 Oct 30 06:24 ..
-rw-r--r-- 1 root root 110712 Oct 15 00:45 libumf.so
-rw-r--r-- 1 root root 110712 Oct 15 00:45 libumf.so.0
-rw-r--r-- 1 root root 110712 Oct 15 00:45 libumf.so.0.9.0

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  No

**Comment by vinser52** [comment]
@bratpiorka after `make isntall` everything is OK (there is only one binary and two symlinks), but in the oneAPI package there are 3 binaries. Is it an issue with BOM files?

**Comment by bratpiorka** [comment]
Yes, this is a bug

**Comment by bratpiorka** [comment]
moved to internal JIRA
